FROM node:22-alpine
ENV CI=true
RUN corepack enable && corepack prepare pnpm@11.1.3 --activate
WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --ignore-scripts --no-frozen-lockfile

COPY prisma ./prisma
RUN npx prisma generate

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate dev --name init 2>/dev/null; pnpm dev --host 0.0.0.0"]
